#include "GBBool.h"
#include "GBReflect.h"

DISABLE_WARNING_PUSH
DISABLE_WARNING_OFFSET_OF_CONDITIONALLY_SUPPORTED

namespace GB
{
	GB_REFLECT_BEGIN(GBBool)
	GB_REFLECT_MEMBER(m_Bool)
	GB_REFLECT_END()
}

DISABLE_WARNING_POP
